[package]
name = "VH1-Bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
opt-level = "z"
panic = "abort"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
serde_json = "1.0.125"
serde = "1.0.208"
futures = "0.3"
reqwest = { version = "0.12.7", features = ["json", "blocking"]}
log = "0.4.22"
once_cell = "1.19"
toml = "0.8.19"
chrono = "0.4.38"
dashmap = "6.0.1"
anyhow = "1.0.82"

[dependencies.poise]
version = "0.6"
default-features = false
features = ["cache", "chrono", "handle_panics",]

[dependencies.songbird]
version = "0.4.3"
default-features = false
features = ["gateway", "serenity", "native", "driver", "receive"]

[dependencies.symphonia]
version = "0.5.2"

[dependencies.tokio]
version = "1.39.3"
features = ["rt-multi-thread", "macros"]

[dependencies.lavalink-rs]
version = "0.13.0"